name: roboshop
services:
  mongodb:
    build: ./mongodb
    image: santu268devops/mongo:v1 # docker build -t santu268devops/mongo:v1
    container_name: mongo
    volumes:
      - mongodb:/data/db
  catalogue:
    build: ./catalogue
    image: santu268devops/catalogue:v1
    container_name: catalogue    
    environment: 
      MONGO: "true"
      MONGO_URL: "mongodb://mongo:27017/catalogue" 
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    image: santu268devops/frontend:v1
    container_name: frontend
    # command: echo "I'm running ${COMPOSE_PROJECT_NAME}"
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment
  redis:
    build: ./redis
    image: santu268devops/redis:v1
    container_name: redis
    volumes:
      - redis:/data
  user:
    build: ./user
    image: santu268devops/user:v1
    container_name: user
    environment: 
      MONGO: "true"
      REDIS_URL: 'redis://redis:6379'
      MONGO_URL: "mongodb://mongodb:27017/users"                 
    depends_on:
      - mongodb
      - redis
  cart:
    build: ./cart
    image: santu268devops/cart:v1
    container_name: cart
    environment:
      REDIS_HOST: redis
      CATALOGUE_HOST: catalogue
      CATALOGUE_PORT: "8080"                 
    depends_on:
      - catalogue
      - redis
  mysql:
    build: ./mysql
    image: santu268devops/mysql:v1
    container_name: mysql    
    command: --mysql-native-password=ON --innodb-lock_wait_timeout=120
    environment:
      MYSQL_ROOT_PASSWORD: RoboShop@1
    volumes:
      - mysql:/var/lib/mysql
  rabbitmq:
    build: ./rabbitmq
    image: santu268devops/rabbitmq:v1
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "roboshop"
      RABBITMQ_DEFAULT_PASS: "roboshop123" 
      volumes:
        - rabbitmq:/var/lib/rabbitmq
  shipping:
    build: ./shipping
    image: santu268devops/shipping:v1
    container_name: shipping
    environment:
      CART_ENDPOINT: "cart:8080"
      DB_HOST: mysql                 
    depends_on:
      - cart
      - mysql
  payment:
    build: ./payment
    image: santu268devops/payment:v1
    container_name: payment
    environment:
      CART_HOST: cart
      CART_PORT: "8080"
      USER_HOST: user
      USER_PORT: "8080"
      AMQP_HOST: "rabbitmq"
      AMQP_USER: "roboshop"
      AMQP_PASS: "roboshop123"                 
    depends_on:
      - cart
      - user
      - rabbitmq
networks:
  default:
    name: roboshop
    driver: bridge
    external: false # if true it should be created manually, if false docker creates this network
volumes:
  mysql
  rabbitmq
  redis
  mongodb
  
